
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: tacocopter_development

test:
  <<: *default
  database: tacocopter_test

production:
  <<: *default
  database: tacocopter_production
  username: tacocopter
  password: <%= ENV['TODO_DATABASE_PASSWORD'] %>
